obstacle_range:  2.5
raytrace_range:  3.0
# footprint:  [[0.1524,0.096],[-0.1524,0.096],[-0.1524,-0.096],[0.1524,-0.096],]
footprint: [[0.4564,0.172],[-0.2024,0.172],[-0.2024,-0.172],[0.4564,-0.172]]
# robot_radius: ir_of_robot
# inflation_radius:  0.03

observation_sources:  laser_scan_sensor #point_cloud_sensor

laser_scan_sensor:  {
    sensor_frame: base_link , 
    data_type: LaserScan, 
    topic: /scan, 
    marking: true, 
    clearing: true
    }

# point_cloud_sensor: {
#     sensor_frame: frame_name, 
#     data_type: PointCloud, 
#     topic: topic_name, 
#     marking: true, 
#     clearing: true}